# Development override for docker-compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
version: '3.8'

services:
  backend:
    build:
      target: builder
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run start:dev"
    stdin_open: true
    tty: true

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true
